CUDA_VISIBLE_DEVICES=1 python3 main_e2e_qp.py \
    --quant_model_path /auto/regrt/sw/dgundimeda/EfficientQAT/output/block_ap_models/Llama-2-7b-w3g64_w2g64 \
    --model_family Llama-2 \
    --wbits 3 \
    --group_size 64 \
    --learning_rate 1e-5 \
    --dataset alpaca \
    --dataset_format alpaca \
    --output_dir ./output/e2e-qp-output/Llama-2-7b-w3g64_w2g64-alpaca-4096_lm_eval \
    --do_train False \
    --do_mmlu_eval True \
    --source_max_len 384 \
    --target_max_len 128 \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --logging_steps 10 \
    --save_strategy steps \
    --evaluation_strategy steps \
    --max_steps 1000 \
    --eval_steps 200 \
    --eval_dataset_size 16 \
    --bf16 \
    --data_seed 42 \
    --max_grad_norm 0.3 \
    --eval_tasks ceval-valid \
    --group_by_length